### ISSUE TITLE
NPM package has not been transpiled

### ISSUE THREAD

**Issue by denkristoffer** [prenaudin/normalize-json-api#1]
Hey! This library looks super helpful, I'm looking forward to trying it out :) I don't know if it's supposed to be ready for use yet, but at the moment it seems like the package on npm isn't being transpiled during prepublishing, I'm getting an `Unexpected token import` error from index.js.

**Comment by prenaudin** [comment]
Hey sachse, yes it's still a work in progress, I am back on it.

**Comment by prenaudin** [comment]
I've just fixed it, could you try and last version 0.1.1?
